#!/bin/bash
#     ////     //  ////     //
#    // //    //  // //    //
#   //  //   //  //  //   //
#  //   //  //  //   //  //
# //    // //  //    // //
#//     ////  //     ////
#
# 20200329 - Vault to NNBackup rsync backup script
# 20200407 - Added logging
# 20200413 - Added vmbackup
# 20200512 - Cleaned up and simplified, removed dry-run logging and added NN stamp
# 20200616 - Added disk confirmation
# 20200628 - Migrated Vault to unRAID NNVault
# 20200701 - Disk mounts within the script
# 20200716 - Added individual VM Backups to 500GB HDD
# 20210228 - Added Wallabag and Proxy VM
# 20210827 - Changed disk layout and backup process
#
#Mount NNVault
sudo mount -t cifs //10.0.100.10/NNVault /nnvault -o credentials=/home/nn/.smbnnvault
#Mount NhuY
sudo mount -t cifs //10.0.100.10/NhuY /nhuy -o credentials=/home/nn/.smbnnvault
echo "-------------------------------------"
echo "--[ Confirm if NNVault is mounted ]--"
echo "-------------------------------------"
if grep -qs '/nnvault ' /proc/mounts; then
  echo "NNVault is Mounted"
  echo "----------------------------------"
  echo "--[ Confirm if NhuY is mounted ]--"
  echo "----------------------------------"
  if grep -qs '/nhuy ' /proc/mounts; then
    echo "NhuY is Mounted"
    echo "--------------------------------"
    echo "--[ Run Dry-Run Rsync? (y/n) ]--"
    echo "--------------------------------"
    read -p ""
    if [[ $REPLY =~ ^[Yy]$ ]]
      then
      echo "-------------------------------"
      echo "--[ Dry-Run NNVault - Files ]--"
      echo "-------------------------------"
      sudo rsync -avnh --progress --delete --stats --ignore-existing --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /nnvault/Files/. /backup1/NNVault/Files
      echo "---------------------------------"
      echo "--[ Dry-run NNVault - Backups ]--"
      echo "---------------------------------"
      sudo rsync -avnh --progress --delete --stats --ignore-existing --ignore-errors -s -e "ssh" --rsync-path="rsync" /nnvault/Backup/. /backup1/NNVault/Backup
      echo "------------------------------"
      echo "--[ Dry-run NhuY - Backups ]--"
      echo "------------------------------"
      sudo rsync -avnh --progress --delete --stats --ignore-existing --ignore-errors -s -e "ssh" --rsync-path="rsync" /nhuy/. /backup1/NhuY
      echo "---------------------"
      echo "--[ Dry-run Music ]--"
      echo "---------------------"
      sudo rsync -avnh --progress --delete --stats --ignore-existing --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /nnvault/Media/Music/. /backup1/music
    fi
    echo "-----------------------------"
    echo "--[ Run Real Rsync? (y/n) ]--"
    echo "-----------------------------"
    read -p ""
    if [[ $REPLY =~ ^[Yy]$ ]]
      then
      #Create backup_tmp.log and backup_page.log
      sudo echo -n > /home/nn/rsync_logs/backup_tmp.log
      sudo echo -n > /home/nn/rsync_logs/backup_page.log
      #Write initial header
      sh -c 'echo "     ////     //  ////     //" >> /home/nn/rsync_logs/backup_page.log'
      sh -c 'echo "    // //    //  // //    //" >> /home/nn/rsync_logs/backup_page.log'
      sh -c 'echo "   //  //   //  //  //   //" >> /home/nn/rsync_logs/backup_page.log'
      sh -c 'echo "  //   //  //  //   //  //" >> /home/nn/rsync_logs/backup_page.log'
      sh -c 'echo " //    // //  //    // //" >> /home/nn/rsync_logs/backup_page.log'
      sh -c 'echo "//     ////  //     ////\n" >> /home/nn/rsync_logs/backup_page.log'
      sh -c 'echo "NNBackup ran backup script on `date`\n" >> /home/nn/rsync_logs/backup_page.log'
      #Runs rsync and writes log to backup_tmp.log
      echo "-----------------------------"
      echo "--[ rSync NNVault - Files ]--"
      echo "-----------------------------"
      sh -c 'echo "-----------------------------" >> /home/nn/rsync_logs/backup_page.log'
      sh -c 'echo "--[ rSync NNVault - Files ]--" >> /home/nn/rsync_logs/backup_page.log'
      sh -c 'echo "-----------------------------" >> /home/nn/rsync_logs/backup_page.log'
      sudo rsync -avh --progress --delete --stats --ignore-existing --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /nnvault/Files/. /backup1/NNVault/Files --log-file=/home/nn/rsync_logs/backup_tmp.log
      tail -n 15 /home/nn/rsync_logs/backup_tmp.log | tee -a /home/nn/rsync_logs/backup_page.log
      echo "-------------------------------"
      echo "--[ rSync NNVault - Backups ]--"
      echo "-------------------------------"
      sh -c 'echo "-------------------------------" >> /home/nn/rsync_logs/backup_page.log'
      sh -c 'echo "--[ rSync NNVault - Backups ]--" >> /home/nn/rsync_logs/backup_page.log'
      sh -c 'echo "-------------------------------" >> /home/nn/rsync_logs/backup_page.log'
      sudo rsync -avh --progress --delete --stats --ignore-existing --ignore-errors -s -e "ssh" --rsync-path="rsync" /nnvault/Backup/. /backup1/NNVault/Backup --log-file=/home/nn/rsync_logs/backup_tmp.log
      tail -n 15 /home/nn/rsync_logs/backup_tmp.log | tee -a /home/nn/rsync_logs/backup_page.log
      echo "----------------------------"
      echo "--[ rSync NhuY - Backups ]--"
      echo "----------------------------"
      sh -c 'echo "----------------------------" >> /home/nn/rsync_logs/backup_page.log'
      sh -c 'echo "--[ rSync NhuY - Backups ]--" >> /home/nn/rsync_logs/backup_page.log'
      sh -c 'echo "----------------------------" >> /home/nn/rsync_logs/backup_page.log'
      sudo rsync -avh --progress --delete --stats --ignore-existing --ignore-errors -s -e "ssh" --rsync-path="rsync" /nhuy/. /backup1/NhuY --log-file=/home/nn/rsync_logs/backup_tmp.log
      tail -n 15 /home/nn/rsync_logs/backup_tmp.log | tee -a /home/nn/rsync_logs/backup_page.log
      echo "-------------------"
      echo "--[ rSync Music ]--"
      echo "-------------------"
      sh -c 'echo "-------------------" >> /home/nn/rsync_logs/backup_page.log'
      sh -c 'echo "--[ rSync Music ]--" >> /home/nn/rsync_logs/backup_page.log'
      sh -c 'echo "-------------------" >> /home/nn/rsync_logs/backup_page.log'
      sudo rsync -avh --progress --delete --stats --ignore-existing --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /nnvault/Media/Music/. /backup1/music --log-file=/home/nn/rsync_logs/backup_tmp.log
      tail -n 15 /home/nn/rsync_logs/backup_tmp.log | tee -a /home/nn/rsync_logs/backup_page.log
    fi
    echo "------------------------------------"
    echo "--[ Dry-Run Mirror Backup? (y/n) ]--"
    echo "------------------------------------"
    read -p ""
    if [[ $REPLY =~ ^[Yy]$ ]]
      then
      echo "-----------------------------"
      echo "--[ Dry-Run Mirror Backup ]--"
      echo "-----------------------------"
      sudo rsync -avnh --progress --delete --stats --ignore-existing --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /backup1/. /backup2
    fi
    echo "-------------------------------------"
    echo "--[ Run Real Mirror Backup? (y/n) ]--"
    echo "-------------------------------------"
    read -p ""
    if [[ $REPLY =~ ^[Yy]$ ]]
      then
      echo "---------------------------"
      echo "--[ rSync Mirror Backup ]--"
      echo "---------------------------"
      sh -c 'echo "---------------------------" >> /home/nn/rsync_logs/backup_page.log'
      sh -c 'echo "--[ rSync Mirror Backup ]--" >> /home/nn/rsync_logs/backup_page.log'
      sh -c 'echo "---------------------------" >> /home/nn/rsync_logs/backup_page.log'
      sudo rsync -avh --progress --delete --stats --ignore-existing --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /backup1/. /backup2 --log-file=/home/nn/rsync_logs/backup_tmp.log
      tail -n 15 /home/nn/rsync_logs/backup_tmp.log | tee -a /home/nn/rsync_logs/backup_page.log
    fi



    echo "----------------------------------"
    echo "--[ Dry-Run Core Backup? (y/n) ]--"
    echo "----------------------------------"
    read -p ""
    if [[ $REPLY =~ ^[Yy]$ ]]
      then
      echo "----------------------------"
      echo "--[ Dry-Run Core - Files ]--"
      echo "----------------------------"
      sudo rsync -avnh --progress --delete --stats --ignore-existing --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /nnvault/Files/. /backup3/Files
      echo "---------------------------"
      echo "--[ Dry-run Core - NhuY ]--"
      echo "---------------------------"
      sudo rsync -avnh --progress --delete --stats --ignore-existing --ignore-errors -s -e "ssh" --rsync-path="rsync" /nhuy/. /backup3/NhuY
    fi
    echo "-----------------------------------"
    echo "--[ Run Real Core Backup? (y/n) ]--"
    echo "-----------------------------------"
    read -p ""
    if [[ $REPLY =~ ^[Yy]$ ]]
      then
      echo "--------------------------"
      echo "--[ rSync Core - Files ]--"
      echo "--------------------------"
      sh -c 'echo "--------------------------" >> /home/nn/rsync_logs/backup_page.log'
      sh -c 'echo "--[ rSync Core - Files ]--" >> /home/nn/rsync_logs/backup_page.log'
      sh -c 'echo "--------------------------" >> /home/nn/rsync_logs/backup_page.log'
      sudo rsync -avh --progress --delete --stats --ignore-existing --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /nnvault/Files/. /backup3/Files --log-file=/home/nn/rsync_logs/backup_tmp.log
      tail -n 15 /home/nn/rsync_logs/backup_tmp.log | tee -a /home/nn/rsync_logs/backup_page.log
      echo "-------------------------"
      echo "--[ rSync Core - NhuY ]--"
      echo "-------------------------"
      sh -c 'echo "-------------------------" >> /home/nn/rsync_logs/backup_page.log'
      sh -c 'echo "--[ rSync Core - NhuY ]--" >> /home/nn/rsync_logs/backup_page.log'
      sh -c 'echo "-------------------------" >> /home/nn/rsync_logs/backup_page.log'
      sudo rsync -avh --progress --delete --stats --ignore-existing --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /nhuy/. /backup3/NhuY --log-file=/home/nn/rsync_logs/backup_tmp.log
      tail -n 15 /home/nn/rsync_logs/backup_tmp.log | tee -a /home/nn/rsync_logs/backup_page.log
    fi
    echo "-------------------------------"
    echo "--[ Dry-Run VMBackup? (y/n) ]--"
    echo "-------------------------------"
    read -p ""
    if [[ $REPLY =~ ^[Yy]$ ]]
      then
      #Dry-run VMBackups rSync
      echo "--[ Dry-run rSync Core.Dashboard ]--"
      VMBACKUP=`ls -t /backup1/Backup/VMBackup/backup/Core.Dashboard/ | head -n1`
      sudo rsync -avnh --progress --delete --stats --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /backup1/Backup/VMBackup/backup/Core.Dashboard/$VMBACKUP/. /backup3/VMBackup/backup/Core.Dashboard/$VMBACKUP/
      echo "--[ Dry-run rSync Core.PFSense ]--"
      VMBACKUP=`ls -t /backup1/Backup/VMBackup/backup/Core.PFSense/ | head -n1`
      sudo rsync -avnh --progress --delete --stats --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /backup1/Backup/VMBackup/backup/Core.PFSense/$VMBACKUP/. /backup3/VMBackup/backup/Core.PFSense/$VMBACKUP/
      echo "--[ Dry-run rSync Core.PiHole1 ]--"
      VMBACKUP=`ls -t /backup1/Backup/VMBackup/backup/Core.PiHole1/ | head -n1`
      sudo rsync -avnh --progress --delete --stats --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /backup1/Backup/VMBackup/backup/Core.PiHole1/$VMBACKUP/. /backup3/VMBackup/backup/Core.PiHole1/$VMBACKUP/
      echo "--[ Dry-run rSync Core.PiHole2 ]--"
      VMBACKUP=`ls -t /backup1/Backup/VMBackup/backup/Core.PiHole2/ | head -n1`
      sudo rsync -avnh --progress --delete --stats --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /backup1/Backup/VMBackup/backup/Core.PiHole2/$VMBACKUP/. /backup3/VMBackup/backup/Core.PiHole2/$VMBACKUP/
      echo "--[ Dry-run rSync Core.Proxy ]--"
      VMBACKUP=`ls -t /backup1/Backup/VMBackup/backup/Core.Proxy/ | head -n1`
      sudo rsync -avnh --progress --delete --stats --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /backup1/Backup/VMBackup/backup/Core.Proxy/$VMBACKUP/. /backup3/VMBackup/backup/Core.Proxy/$VMBACKUP/
      echo "--[ Dry-run rSync Core.RelayVPN ]--"
      VMBACKUP=`ls -t /backup1/Backup/VMBackup/backup/Core.RelayVPN/ | head -n1`
      sudo rsync -avnh --progress --delete --stats --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /backup1/Backup/VMBackup/backup/Core.RelayVPN/$VMBACKUP/. /backup3/VMBackup/backup/Core.RelayVPN/$VMBACKUP/
      echo "--[ Dry-run rSync Core.UniFi ]--"
      VMBACKUP=`ls -t /backup1/Backup/VMBackup/backup/Core.UniFi/ | head -n1`
      sudo rsync -avnh --progress --delete --stats --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /backup1/Backup/VMBackup/backup/Core.UniFi/$VMBACKUP/. /backup3/VMBackup/backup/Core.UniFi/$VMBACKUP/
      echo "--[ Dry-run rSync DMZ.ReverseProxy ]--"
      VMBACKUP=`ls -t /backup1/Backup/VMBackup/backup/DMZ.ReverseProxy/ | head -n1`
      sudo rsync -avnh --progress --delete --stats --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /backup1/Backup/VMBackup/backup/DMZ.ReverseProxy/$VMBACKUP/. /backup3/VMBackup/backup/DMZ.ReverseProxy/$VMBACKUP/
      echo "--[ Dry-run rSync HOME.Genesis ]--"
      VMBACKUP=`ls -t /backup1/Backup/VMBackup/backup/HOME.Genesis/ | head -n1`
      sudo rsync -avnh --progress --delete --stats --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /backup1/Backup/VMBackup/backup/HOME.Genesis/$VMBACKUP/. /backup3/VMBackup/backup/HOME.Genesis/$VMBACKUP/
      echo "--[ Dry-run rSync HOME.Plex ]--"
      VMBACKUP=`ls -t /backup1/Backup/VMBackup/backup/HOME.Plex/ | head -n1`
      sudo rsync -avnh --progress --delete --stats --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /backup1/Backup/VMBackup/backup/HOME.Plex/$VMBACKUP/. /backup3/VMBackup/backup/HOME.Plex/$VMBACKUP/
      echo "--[ Dry-run rSync HOME.RemoteBackup ]--"
      VMBACKUP=`ls -t /backup1/Backup/VMBackup/backup/HOME.RemoteBackup/ | head -n1`
      sudo rsync -avnh --progress --delete --stats --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /backup1/Backup/VMBackup/backup/HOME.RemoteBackup/$VMBACKUP/. /backup3/VMBackup/backup/HOME.RemoteBackup/$VMBACKUP/
      echo "--[ Dry-run rSync WEB.BookStack ]--"
      VMBACKUP=`ls -t /backup1/Backup/VMBackup/backup/WEB.BookStack/ | head -n1`
      sudo rsync -avnh --progress --delete --stats --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /backup1/Backup/VMBackup/backup/WEB.BookStack/$VMBACKUP/. /backup3/VMBackup/backup/WEB.BookStack/$VMBACKUP/
      echo "--[ Dry-run rSync WEB.Index ]--"
      VMBACKUP=`ls -t /backup1/Backup/VMBackup/backup/WEB.Index/ | head -n1`
      sudo rsync -avnh --progress --delete --stats --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /backup1/Backup/VMBackup/backup/WEB.Index/$VMBACKUP/. /backup3/VMBackup/backup/WEB.Index/$VMBACKUP/
      echo "--[ Dry-run rSync WEB.NextCloud ]--"
      VMBACKUP=`ls -t /backup1/Backup/VMBackup/backup/WEB.NextCloud/ | head -n1`
      sudo rsync -avnh --progress --delete --stats --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /backup1/Backup/VMBackup/backup/WEB.NextCloud/$VMBACKUP/. /backup3/VMBackup/backup/WEB.NextCloud/$VMBACKUP/
    fi
    echo "---------------------------------"
    echo "--[ Run rSync VMBackup? (y/n) ]--"
    echo "---------------------------------"
    read -p ""
    if [[ $REPLY =~ ^[Yy]$ ]]
      then
      #Get latest folder within VM directory, delete previous backups, and rSync latest backup
      echo "--[ Backup Core.Dashboard ]--"
      VMBACKUP=`ls -t /backup1/Backup/VMBackup/backup/Core.Dashboard/ | head -n1`
      sh -c 'echo "--[ Backup Core.Dashboard ]--" >> /home/nn/rsync_logs/backup_page.log'
      sudo rm -rv /vmbackup/VMBackup/backup/Core.Dashboard/* >> /home/nn/rsync_logs/backup_page.log
      sudo rsync -avh --progress --delete --stats --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /backup1/Backup/VMBackup/backup/Core.Dashboard/$VMBACKUP/. /backup3/VMBackup/backup/Core.Dashboard/$VMBACKUP/ --log-file=/home/nn/rsync_logs/backup_tmp.log
      tail -n 2 /home/nn/rsync_logs/backup_tmp.log | tee -a /home/nn/rsync_logs/backup_page.log
      echo "--[ Backup Core.PFSense ]--"
      VMBACKUP=`ls -t /backup1/Backup/VMBackup/backup/Core.PFSense/ | head -n1`
      sh -c 'echo "--[ Backup Core.PFSense ]--" >> /home/nn/rsync_logs/backup_page.log'
      sudo rm -rv /vmbackup/VMBackup/backup/Core.PFSense/* >> /home/nn/rsync_logs/backup_page.log
      sudo rsync -avh --progress --delete --stats --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /backup1/Backup/VMBackup/backup/Core.PFSense/$VMBACKUP/. /backup3/VMBackup/backup/Core.PFSense/$VMBACKUP/ --log-file=/home/nn/rsync_logs/backup_tmp.log
      tail -n 2 /home/nn/rsync_logs/backup_tmp.log | tee -a /home/nn/rsync_logs/backup_page.log
      echo "--[ Backup Core.PiHole1 ]--"
      VMBACKUP=`ls -t /backup1/Backup/VMBackup/backup/Core.PiHole1/ | head -n1`
      sh -c 'echo "--[ Backup Core.PiHole1 ]--" >> /home/nn/rsync_logs/backup_page.log'
      sudo rm -rv /vmbackup/VMBackup/backup/Core.PiHole1/* >> /home/nn/rsync_logs/backup_page.log
      sudo rsync -avh --progress --delete --stats --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /backup1/Backup/VMBackup/backup/Core.PiHole1/$VMBACKUP/. /backup3/VMBackup/backup/Core.PiHole1/$VMBACKUP/ --log-file=/home/nn/rsync_logs/backup_tmp.log
      tail -n 2 /home/nn/rsync_logs/backup_tmp.log | tee -a /home/nn/rsync_logs/backup_page.log
      echo "--[ Backup Core.PiHole2 ]--"
      VMBACKUP=`ls -t /backup1/Backup/VMBackup/backup/Core.PiHole2/ | head -n1`
      sh -c 'echo "--[ Backup Core.PiHole2 ]--" >> /home/nn/rsync_logs/backup_page.log'
      sudo rm -rv /vmbackup/VMBackup/backup/Core.PiHole2/* >> /home/nn/rsync_logs/backup_page.log
      sudo rsync -avh --progress --delete --stats --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /backup1/Backup/VMBackup/backup/Core.PiHole2/$VMBACKUP/. /backup3/VMBackup/backup/Core.PiHole2/$VMBACKUP/ --log-file=/home/nn/rsync_logs/backup_tmp.log
      tail -n 2 /home/nn/rsync_logs/backup_tmp.log | tee -a /home/nn/rsync_logs/backup_page.log
      echo "--[ Backup Core.Proxy ]--"
      VMBACKUP=`ls -t /backup1/Backup/VMBackup/backup/Core.Proxy/ | head -n1`
      sh -c 'echo "--[ Backup Core.Proxy ]--" >> /home/nn/rsync_logs/backup_page.log'
      sudo rm -rv /vmbackup/VMBackup/backup/Core.Proxy/* >> /home/nn/rsync_logs/backup_page.log
      sudo rsync -avh --progress --delete --stats --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /backup1/Backup/VMBackup/backup/Core.Proxy/$VMBACKUP/. /backup3/VMBackup/backup/Core.Proxy/$VMBACKUP/ --log-file=/home/nn/rsync_logs/backup_tmp.log
      tail -n 2 /home/nn/rsync_logs/backup_tmp.log | tee -a /home/nn/rsync_logs/backup_page.log
      echo "--[ Backup Core.RelayVPN ]--"
      VMBACKUP=`ls -t /backup1/Backup/VMBackup/backup/Core.RelayVPN/ | head -n1`
      sh -c 'echo "--[ Backup Core.RelayVPN ]--" >> /home/nn/rsync_logs/backup_page.log'
      sudo rm -rv /vmbackup/VMBackup/backup/Core.RelayVPN/* >> /home/nn/rsync_logs/backup_page.log
      sudo rsync -avh --progress --delete --stats --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /backup1/Backup/VMBackup/backup/Core.RelayVPN/$VMBACKUP/. /backup3/VMBackup/backup/Core.RelayVPN/$VMBACKUP/ --log-file=/home/nn/rsync_logs/backup_tmp.log
      tail -n 2 /home/nn/rsync_logs/backup_tmp.log | tee -a /home/nn/rsync_logs/backup_page.log
      echo "--[ Backup Core.UniFi ]--"
      VMBACKUP=`ls -t /backup1/Backup/VMBackup/backup/Core.UniFi/ | head -n1`
      sh -c 'echo "--[ Backup Core.UniFi ]--" >> /home/nn/rsync_logs/backup_page.log'
      sudo rm -rv /vmbackup/VMBackup/backup/Core.UniFi/* >> /home/nn/rsync_logs/backup_page.log
      sudo rsync -avh --progress --delete --stats --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /backup1/Backup/VMBackup/backup/Core.UniFi/$VMBACKUP/. /backup3/VMBackup/backup/Core.UniFi/$VMBACKUP/ --log-file=/home/nn/rsync_logs/backup_tmp.log
      tail -n 2 /home/nn/rsync_logs/backup_tmp.log | tee -a /home/nn/rsync_logs/backup_page.log
      echo "--[ Backup DMZ.ReverseProxy ]--"
      VMBACKUP=`ls -t /backup1/Backup/VMBackup/backup/DMZ.ReverseProxy/ | head -n1`
      sh -c 'echo "--[ Backup DMZ.ReverseProxy ]--" >> /home/nn/rsync_logs/backup_page.log'
      sudo rm -rv /vmbackup/VMBackup/backup/DMZ.ReverseProxy/* >> /home/nn/rsync_logs/backup_page.log
      sudo rsync -avh --progress --delete --stats --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /backup1/Backup/VMBackup/backup/DMZ.ReverseProxy/$VMBACKUP/. /backup3/VMBackup/backup/DMZ.ReverseProxy/$VMBACKUP/ --log-file=/home/nn/rsync_logs/backup_tmp.log
      tail -n 2 /home/nn/rsync_logs/backup_tmp.log | tee -a /home/nn/rsync_logs/backup_page.log
      echo "--[ Backup HOME.Genesis ]--"
      VMBACKUP=`ls -t /backup1/Backup/VMBackup/backup/HOME.Genesis/ | head -n1`
      sh -c 'echo "--[ Backup HOME.Genesis ]--" >> /home/nn/rsync_logs/backup_page.log'
      sudo rm -rv /vmbackup/VMBackup/backup/HOME.Genesis/* >> /home/nn/rsync_logs/backup_page.log
      sudo rsync -avh --progress --delete --stats --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /backup1/Backup/VMBackup/backup/HOME.Genesis/$VMBACKUP/. /backup3/VMBackup/backup/HOME.Genesis/$VMBACKUP/ --log-file=/home/nn/rsync_logs/backup_tmp.log
      tail -n 2 /home/nn/rsync_logs/backup_tmp.log | tee -a /home/nn/rsync_logs/backup_page.log
      echo "--[ Backup HOME.Plex ]--"
      VMBACKUP=`ls -t /backup1/Backup/VMBackup/backup/HOME.Plex/ | head -n1`
      sh -c 'echo "--[ Backup HOME.Plex ]--" >> /home/nn/rsync_logs/backup_page.log'
      sudo rm -rv /vmbackup/VMBackup/backup/HOME.Plex/* >> /home/nn/rsync_logs/backup_page.log
      sudo rsync -avh --progress --delete --stats --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /backup1/Backup/VMBackup/backup/HOME.Plex/$VMBACKUP/. /backup3/VMBackup/backup/HOME.Plex/$VMBACKUP/ --log-file=/home/nn/rsync_logs/backup_tmp.log
      tail -n 2 /home/nn/rsync_logs/backup_tmp.log | tee -a /home/nn/rsync_logs/backup_page.log
      echo "--[ Backup HOME.RemoteBackup ]--"
      VMBACKUP=`ls -t /backup1/Backup/VMBackup/backup/HOME.RemoteBackup/ | head -n1`
      sh -c 'echo "--[ Backup HOME.RemoteBackup ]--" >> /home/nn/rsync_logs/backup_page.log'
      sudo rm -rv /vmbackup/VMBackup/backup/HOME.RemoteBackup/* >> /home/nn/rsync_logs/backup_page.log
      sudo rsync -avh --progress --delete --stats --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /backup1/Backup/VMBackup/backup/HOME.RemoteBackup/$VMBACKUP/. /backup3/VMBackup/backup/HOME.RemoteBackup/$VMBACKUP/ --log-file=/home/nn/rsync_logs/backup_tmp.log
      tail -n 2 /home/nn/rsync_logs/backup_tmp.log | tee -a /home/nn/rsync_logs/backup_page.log
      echo "--[ Backup WEB.BookStack ]--"
      VMBACKUP=`ls -t /backup1/Backup/VMBackup/backup/WEB.BookStack/ | head -n1`
      sh -c 'echo "--[ Backup WEB.BookStack ]--" >> /home/nn/rsync_logs/backup_page.log'
      sudo rm -rv /vmbackup/VMBackup/backup/WEB.BookStack/* >> /home/nn/rsync_logs/backup_page.log
      sudo rsync -avh --progress --delete --stats --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /backup1/Backup/VMBackup/backup/WEB.BookStack/$VMBACKUP/. /backup3/VMBackup/backup/WEB.BookStack/$VMBACKUP/ --log-file=/home/nn/rsync_logs/backup_tmp.log
      tail -n 2 /home/nn/rsync_logs/backup_tmp.log | tee -a /home/nn/rsync_logs/backup_page.log
      echo "--[ Backup WEB.Index ]--"
      VMBACKUP=`ls -t /backup1/Backup/VMBackup/backup/WEB.Index/ | head -n1`
      sh -c 'echo "--[ Backup WEB.Index ]--" >> /home/nn/rsync_logs/backup_page.log'
      sudo rm -rv /vmbackup/VMBackup/backup/WEB.Index/* >> /home/nn/rsync_logs/backup_page.log
      sudo rsync -avh --progress --delete --stats --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /backup1/Backup/VMBackup/backup/WEB.Index/$VMBACKUP/. /backup3/VMBackup/backup/WEB.Index/$VMBACKUP/ --log-file=/home/nn/rsync_logs/backup_tmp.log
      tail -n 2 /home/nn/rsync_logs/backup_tmp.log | tee -a /home/nn/rsync_logs/backup_page.log
      echo "--[ Backup WEB.NextCloud ]--"
      VMBACKUP=`ls -t /backup1/Backup/VMBackup/backup/WEB.NextCloud/ | head -n1`
      sh -c 'echo "--[ Backup WEB.NextCloud ]--" >> /home/nn/rsync_logs/backup_page.log'
      sudo rm -rv /vmbackup/VMBackup/backup/WEB.NextCloud/* >> /home/nn/rsync_logs/backup_page.log
      sudo rsync -avh --progress --delete --stats --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /backup1/Backup/VMBackup/backup/WEB.NextCloud/$VMBACKUP/. /backup3/VMBackup/backup/WEB.NextCloud/$VMBACKUP/ --log-file=/home/nn/rsync_logs/backup_tmp.log
      tail -n 2 /home/nn/rsync_logs/backup_tmp.log | tee -a /home/nn/rsync_logs/backup_page.log
    fi
    #Copy backup_page with date stamp for archive on server
    sudo cp /home/nn/rsync_logs/backup_page.log /home/nn/rsync_logs/backup_"$(date +%Y-%m-%d_%H%M%S)".log
    #Copy backup_page to NNBackup logging folder
    sudo cp /home/nn/rsync_logs/backup_page.log /nnvault/Backup/NNServer/NNBackup/Logs/backup_"$(date +%Y-%m-%d_%H%M%S)".log
  else
    echo "Error : NhuY Not Mounted"
  fi
else
  echo "Error : NNVault Not Mounted"
fi
#delete temp files
sudo rm /home/nn/rsync_logs/backup_tmp.log
sudo rm /home/nn/rsync_logs/backup_page.log
#Unmount NNVault
sudo umount -t cifs //10.0.100.10/NNVault
sudo umount -t cifs //10.0.100.10/NhuY