#!/bin/bash
#   _  ___  __                         
#  / |/ / |/ /
# /    /    /   
#/_/|_/_/|_/  
#
########################################################################################
#
# 20200329 - Vault to NNBackup rsync backup script
# 20200407 - Added logging
# 20200413 - Added vmbackup
# 20200512 - Cleaned up and simplified, removed dry-run logging and added NN stamp
# 20200616 - Added disk confirmation
# 20200628 - Migrated Vault to unRAID NNVault
# 20200701 - Disk mounts within the script
# 20200716 - Added individual VM Backups to 500GB HDD
# 20210228 - Added Wallabag and Proxy VM
# 20210827 - Changed disk layout and backup process
# 20220111 - Migrated NNBackup from Q6600/ATI to R230
# 20220301 - Condensed Dry-Run and Real-Run to one-shot
#
#########################################################################################
#
#Create backup_tmp.log and backup_page.log
sudo echo -n > /home/nn/rsync_logs/backup_tmp.log
sudo echo -n > /home/nn/rsync_logs/backup_page.log
#Write initial header
sh -c 'echo "     ////     //  ////     //" >> /home/nn/rsync_logs/backup_page.log'
sh -c 'echo "    // //    //  // //    //" >> /home/nn/rsync_logs/backup_page.log'
sh -c 'echo "   //  //   //  //  //   //" >> /home/nn/rsync_logs/backup_page.log'
sh -c 'echo "  //   //  //  //   //  //" >> /home/nn/rsync_logs/backup_page.log'
sh -c 'echo " //    // //  //    // //" >> /home/nn/rsync_logs/backup_page.log'
sh -c 'echo "//     ////  //     ////\n" >> /home/nn/rsync_logs/backup_page.log'
sh -c 'echo "NNBackup ran backup script on `date`\n" >> /home/nn/rsync_logs/backup_page.log'
#Mount NNVault
sudo mount -t cifs //10.0.100.10/NNVault /nnvault -o credentials=/home/nn/.smbnnvault,noserverino,vers=3.1.1
#Mount NhuY
sudo mount -t cifs //10.0.100.10/NhuY /nhuy -o credentials=/home/nn/.smbnnvault,noserverino,vers=3.1.1
echo "-------------------------------------"
echo "--[ Confirm if NNVault is mounted ]--"
echo "-------------------------------------"
if grep -qs '/nnvault ' /proc/mounts; then
  echo "NNVault is Mounted"
  sh -c 'echo "NNVault is Mounted" >> /home/nn/rsync_logs/backup_page.log'
  echo "----------------------------------"
  echo "--[ Confirm if NhuY is mounted ]--"
  echo "----------------------------------"
  if grep -qs '/nhuy ' /proc/mounts; then
    echo "NhuY is Mounted"
    sh -c 'echo "NhuY is Mounted\n" >> /home/nn/rsync_logs/backup_page.log'
    echo "--------------------------------"
    echo "--[ Run Dry-Run Rsync? (y/n) ]--"
    echo "--------------------------------"
    read -p ""
    if [[ $REPLY =~ ^[Yy]$ ]]
      then
      echo "-------------------------------"
      echo "--[ Dry-Run NNVault - Files ]--"
      echo "-------------------------------"
      sudo rsync -avnh --progress --delete --stats --ignore-existing --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /nnvault/Files/. /backup1/NNVault/Files
      echo "---------------------------------"
      echo "--[ Dry-run NNVault - Backups ]--"
      echo "---------------------------------"
      sudo rsync -avnh --progress --delete --stats --ignore-existing --ignore-errors -s -e "ssh" --rsync-path="rsync" /nnvault/Backup/. /backup1/NNVault/Backup
      echo "------------------------------"
      echo "--[ Dry-run NhuY - Backups ]--"
      echo "------------------------------"
      sudo rsync -avnh --progress --delete --stats --ignore-existing --ignore-errors -s -e "ssh" --rsync-path="rsync" /nhuy/. /backup1/NhuY
      echo "---------------------"
      echo "--[ Dry-run Music ]--"
      echo "---------------------"
      sudo rsync -avnh --progress --delete --stats --ignore-existing --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /nnvault/Media/Music/. /backup1/music
      echo "-----------------------------"
      echo "--[ Dry-Run Mirror Backup ]--"
      echo "-----------------------------"
      sudo rsync -avnh --progress --delete --stats --ignore-existing --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /backup1/. /backup2
    fi
    echo "-----------------------------"
    echo "--[ Run Real Rsync? (y/n) ]--"
    echo "-----------------------------"
    read -p ""
    if [[ $REPLY =~ ^[Yy]$ ]]
      then
      #Runs rsync and writes log to backup_tmp.log
      echo "-----------------------------"
      echo "--[ rSync NNVault - Files ]--"
      echo "-----------------------------"
      sh -c 'echo "-----------------------------" >> /home/nn/rsync_logs/backup_page.log'
      sh -c 'echo "--[ rSync NNVault - Files ]--" >> /home/nn/rsync_logs/backup_page.log'
      sh -c 'echo "-----------------------------" >> /home/nn/rsync_logs/backup_page.log'
      sudo rsync -avh --progress --delete --stats --ignore-existing --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /nnvault/Files/. /backup1/NNVault/Files --log-file=/home/nn/rsync_logs/backup_tmp.log
      tail -n 15 /home/nn/rsync_logs/backup_tmp.log | tee -a /home/nn/rsync_logs/backup_page.log
      echo "-------------------------------"
      echo "--[ rSync NNVault - Backups ]--"
      echo "-------------------------------"
      sh -c 'echo "-------------------------------" >> /home/nn/rsync_logs/backup_page.log'
      sh -c 'echo "--[ rSync NNVault - Backups ]--" >> /home/nn/rsync_logs/backup_page.log'
      sh -c 'echo "-------------------------------" >> /home/nn/rsync_logs/backup_page.log'
      sudo rsync -avh --progress --delete --stats --ignore-existing --ignore-errors -s -e "ssh" --rsync-path="rsync" /nnvault/Backup/. /backup1/NNVault/Backup --log-file=/home/nn/rsync_logs/backup_tmp.log
      tail -n 15 /home/nn/rsync_logs/backup_tmp.log | tee -a /home/nn/rsync_logs/backup_page.log
      echo "----------------------------"
      echo "--[ rSync NhuY - Backups ]--"
      echo "----------------------------"
      sh -c 'echo "----------------------------" >> /home/nn/rsync_logs/backup_page.log'
      sh -c 'echo "--[ rSync NhuY - Backups ]--" >> /home/nn/rsync_logs/backup_page.log'
      sh -c 'echo "----------------------------" >> /home/nn/rsync_logs/backup_page.log'
      sudo rsync -avh --progress --delete --stats --ignore-existing --ignore-errors -s -e "ssh" --rsync-path="rsync" /nhuy/. /backup1/NhuY --log-file=/home/nn/rsync_logs/backup_tmp.log
      tail -n 15 /home/nn/rsync_logs/backup_tmp.log | tee -a /home/nn/rsync_logs/backup_page.log
      echo "-------------------"
      echo "--[ rSync Music ]--"
      echo "-------------------"
      sh -c 'echo "-------------------" >> /home/nn/rsync_logs/backup_page.log'
      sh -c 'echo "--[ rSync Music ]--" >> /home/nn/rsync_logs/backup_page.log'
      sh -c 'echo "-------------------" >> /home/nn/rsync_logs/backup_page.log'
      sudo rsync -avh --progress --delete --stats --ignore-existing --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /nnvault/Media/Music/. /backup1/music --log-file=/home/nn/rsync_logs/backup_tmp.log
      tail -n 15 /home/nn/rsync_logs/backup_tmp.log | tee -a /home/nn/rsync_logs/backup_page.log
      echo "---------------------------"
      echo "--[ rSync Mirror Backup ]--"
      echo "---------------------------"
      sh -c 'echo "---------------------------" >> /home/nn/rsync_logs/backup_page.log'
      sh -c 'echo "--[ rSync Mirror Backup ]--" >> /home/nn/rsync_logs/backup_page.log'
      sh -c 'echo "---------------------------" >> /home/nn/rsync_logs/backup_page.log'
      sudo rsync -avh --progress --delete --stats --ignore-existing --ignore-errors -s -e "ssh" --rsync-path="sudo rsync" /backup1/. /backup2 --log-file=/home/nn/rsync_logs/backup_tmp.log
      #Logging Backup
      tail -n 15 /home/nn/rsync_logs/backup_tmp.log | tee -a /home/nn/rsync_logs/backup_page.log
      #Copy backup_page with date stamp for archive on server
      sudo cp /home/nn/rsync_logs/backup_page.log /home/nn/rsync_logs/backup_"$(date +%Y-%m-%d_%H%M%S)".log
      #Copy backup_page to NNBackup logging folder
      sudo cp /home/nn/rsync_logs/backup_page.log /nnvault/Backup/NNServer/NNBackup/Logs/backup_"$(date +%Y-%m-%d_%H%M%S)".log
    fi
  else
    echo "Error : NhuY Not Mounted"
    sh -c 'echo "NhuY Not Mounted" >> /home/nn/rsync_logs/backup_page.log'
  fi
else
  echo "Error : NNVault Not Mounted"
  sh -c 'echo "NNVault Not Mounted" >> /home/nn/rsync_logs/backup_page.log'
fi
#delete temp files
sudo rm /home/nn/rsync_logs/backup_tmp.log
sudo rm /home/nn/rsync_logs/backup_page.log
#Unmount NNVault
sudo umount -t cifs //10.0.100.10/NNVault
sudo umount -t cifs //10.0.100.10/NhuY
echo "----------------------------"
echo "--[ Shutdown R230? (y/n) ]--"
echo "----------------------------"
read -p ""
if [[ $REPLY =~ ^[Yy]$ ]]
  then
  sh /home/nn/poweroff
fi