#!/bin/bash
#   _  ___  __                         
#  / |/ / |/ /
# /    /    /   
#/_/|_/_/|_/  
#
# 20200329 - First script for updating nnbackup
# 20200319 - Checks logs for maintenance
# 20200319 - Added testing disk access speed
#            https://www.debian.org/doc/manuals/debian-reference/ch09.en.html
# 20200515 - Refreshed look, added Debian Versioning
# 20220117 - Updated for R230
#
echo "------------------------------------------"
echo "--[ Debian Version $(cat /etc/debian_version), Update? (y/n) ]--"
echo "------------------------------------------"
read -p ""
if [[ $REPLY =~ ^[Yy]$ ]]
then
  echo "-----------------------"
  echo "--[ Updating Debian ]--"
  echo "-----------------------"
  sudo apt update
  echo "------------------------"
  echo "--[ Upgrading Debian ]--"
  echo "------------------------"
  sudo apt upgrade
  echo "-------------------------"
  echo "--[ Running autoclean ]--"
  echo "-------------------------"
  sudo apt autoclean
  echo "--------------------------"
  echo "--[ Running autoremove ]--"
  echo "--------------------------"
  sudo apt autoremove
fi
echo "------------------------"
echo "--[ Updating mlocate ]--"
echo "------------------------"
sudo updatedb
echo "-------------------------"
echo "--[ Check Logs? (y/n) ]--"
echo "-------------------------"
read -p ""
if [[ $REPLY =~ ^[Yy]$ ]]
then
  echo "---------------------------------------"
  echo "--[ Checking Unattended Updates log ]--"
  echo "---------------------------------------"
  sudo tail -n 5 /var/log/unattended-upgrades/unattended-upgrades.log
  echo "---------------------------------------"
  echo "--[ Checking if fail2ban is running ]--"
  echo "---------------------------------------"
  sudo fail2ban-client status
  echo "---------------------------"
  echo "--[ Checking UFW status ]--"
  echo "---------------------------"
  sudo ufw status
  echo "--------------------------------------"
  echo "--[ Check Disk Access Speed? (y/n) ]--"
  echo "--------------------------------------"
  read -p ""
  if [[ $REPLY =~ ^[Yy]$ ]]
  then
    echo "---------------------------------"
    echo "--[ Testing disk access speed ]--"
    echo "---------------------------------"
    #Backup1
    sudo hdparm -tT /dev/sdb1
    #Backup2
    sudo hdparm -tT /dev/sdc1
  fi
  echo "--------------------------------------"
  echo "--[ Check SMART data on drives? (y/n) ]--"
  echo "--------------------------------------"
  read -p ""
  if [[ $REPLY =~ ^[Yy]$ ]]
  then
    echo "---------------------------"
    echo "--[ Checking SMART data ]--"
    echo "---------------------------"
    #Backup1
    sudo smartctl -a /dev/sdb1
    #Backup2
    sudo smartctl -a /dev/sdc1
  fi
echo "--------------------------------"
  echo "--[ Run rkhunter scan? (y/n) ]--"
  echo "--------------------------------"
  read -p ""
  if [[ $REPLY =~ ^[Yy]$ ]]
  then
    echo "-----------------------------"
    echo "--[ Running rkhunter scan ]--"
    echo "-----------------------------"
    sudo rkhunter --check --rwo
  fi
fi

