#!/bin/bash
#     ////     //  ////     //
#    // //    //  // //    //
#   //  //   //  //  //   //
#  //   //  //  //   //  //
# //    // //  //    // //
#//     ////  //     ////
#
# 20200329 - First script for updating nnbackup
# 20200319 - Checks logs for maintenance
# 20200319 - Added testing disk access speed
#            https://www.debian.org/doc/manuals/debian-reference/ch09.en.html
echo "------------------------------------------------------------------------"
echo "Updating Debian..."
echo "------------------------------------------------------------------------"
sudo apt-get update
echo "------------------------------------------------------------------------"
echo "Upgrading Debian..."
echo "------------------------------------------------------------------------"
sudo apt-get upgrade
echo "------------------------------------------------------------------------"
echo "Running autoclean..."
echo "------------------------------------------------------------------------"
sudo apt-get autoclean
echo "------------------------------------------------------------------------"
echo "Updating mlocate..."
echo "------------------------------------------------------------------------"
sudo updatedb
echo "------------------------------------------------------------------------"
echo "Remember to check logs!"
echo "------------------------------------------------------------------------"
read -p "Check logs? (y/n)"
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
  echo "------------------------------------------------------------------------"
  echo "Checking Unattended Updates log..."
  echo "------------------------------------------------------------------------"
  sudo tail -n 5 /var/log/dpkg.log
  echo "------------------------------------------------------------------------"
  echo "Checking if fail2ban is running..."
  echo "------------------------------------------------------------------------"
  sudo fail2ban-client status
  echo "------------------------------------------------------------------------"
  echo "Checking ufw status..."
  echo "------------------------------------------------------------------------"
  sudo ufw status
  echo "------------------------------------------------------------------------"
  echo "Testing disk access speed..."
  echo "------------------------------------------------------------------------"
  sudo hdparm -tT /dev/sda1
  sudo hdparm -tT /dev/sdc1
  sudo hdparm -tT /dev/sdd1
  sudo hdparm -tT /dev/sde1
  sudo hdparm -tT /dev/sdf1
  sudo hdparm -tT /dev/sdb1
  
  echo "------------------------------------------------------------------------"
  echo "Check SMART reading on drive..."
  echo "------------------------------------------------------------------------"
  sudo smartctl -a /dev/sda1
  sudo smartctl -a /dev/sdc1
  sudo smartctl -a /dev/sdd1
  sudo smartctl -a /dev/sde1
  sudo smartctl -a /dev/sdf1
  sudo smartctl -a /dev/sdb1
fi
