#!/bin/bash
#     ////     //  ////     //
#    // //    //  // //    //
#   //  //   //  //  //   //
#  //   //  //  //   //  //
# //    // //  //    // //
#//     ////  //     ////
#
# 20200512 - Created cron_backup for cronjob
# 20200616 - Added disk confirmation
#
#NNVault disk confirmation
if grep -qs '/nnvault ' /proc/mounts; then
  echo "NNVault is Mounted"
  #Create backup_tmp.log and backup_page.log
  echo -n > /home/nn/rsync_logs/backup_tmp.log
  echo -n > /home/nn/rsync_logs/backup_page.log
  #Write initial header
  sh -c 'echo "     ////     //  ////     //" >> /home/nn/rsync_logs/backup_page.log'
  sh -c 'echo "    // //    //  // //    //" >> /home/nn/rsync_logs/backup_page.log'
  sh -c 'echo "   //  //   //  //  //   //" >> /home/nn/rsync_logs/backup_page.log'
  sh -c 'echo "  //   //  //  //   //  //" >> /home/nn/rsync_logs/backup_page.log'
  sh -c 'echo " //    // //  //    // //" >> /home/nn/rsync_logs/backup_page.log'
  sh -c 'echo "//     ////  //     ////\n" >> /home/nn/rsync_logs/backup_page.log'
  sh -c 'echo "NNBackup ran backup script on `date`\n" >> /home/nn/rsync_logs/backup_page.log'
  #Runs rsync and writes log to backup_tmp.log
  echo "---------------------------------------------"
  echo "--[ Backup /nnvault/Files/. > /backup1/n1 ]--"
  echo "---------------------------------------------"
  sh -c 'echo "---------------------------------------------" >> /home/nn/rsync_logs/backup_page.log'
  sh -c 'echo "--[ Backup /nnvault/Files/. > /backup1/n1 ]--" >> /home/nn/rsync_logs/backup_page.log'
  sh -c 'echo "---------------------------------------------" >> /home/nn/rsync_logs/backup_page.log'
  rsync -avh --progress --delete --stats --ignore-existing --ignore-errors -s -e "ssh" --rsync-path="rsync" /nnvault/Files/. /backup1/Files --log-file=/home/nn/rsync_logs/backup_tmp.log
  tail -n 15 /home/nn/rsync_logs/backup_tmp.log | tee -a /home/nn/rsync_logs/backup_page.log
  echo "------------------------------------------------------"
  echo "--[ Backup /nnvault/VMBackup/. > /backup1/VMBackup ]--"
  echo "------------------------------------------------------"
  sh -c 'echo "------------------------------------------------------" >> /home/nn/rsync_logs/backup_page.log'
  sh -c 'echo "--[ Backup /nnvault/VMBackup/. > /backup1/VMBackup ]--" >> /home/nn/rsync_logs/backup_page.log'
  sh -c 'echo "------------------------------------------------------" >> /home/nn/rsync_logs/backup_page.log'
  rsync -avh --progress --stats --ignore-existing --ignore-errors -s -e "ssh" --rsync-path="rsync" /nnvault/VMBackup/. /backup1/VMBackup --log-file=/home/nn/rsync_logs/backup_tmp.log
  tail -n 15 /home/nn/rsync_logs/backup_tmp.log | tee -a /home/nn/rsync_logs/backup_page.log
  echo "---------------------------------------------------------------------"
  echo "--[ Backup /backup1/VMBackup/backup/. > /vmbackup/VMBackup/backup ]--"
  echo "---------------------------------------------------------------------"
  sh -c 'echo "---------------------------------------------------------------------" >> /home/nn/rsync_logs/backup_page.log'
  sh -c 'echo "--[ Backup /backup1/VMBackup/backup/. > /vmbackup/VMBackup/backup ]--" >> /home/nn/rsync_logs/backup_page.log'
  sh -c 'echo "---------------------------------------------------------------------" >> /home/nn/rsync_logs/backup_page.log'
  rsync -avh --progress --stats --ignore-existing --ignore-errors -s -e "ssh" --rsync-path="rsync" /backup1/VMBackup/backup/. /vmbackup/VMBackup/backup --log-file=/home/nn/rsync_logs/backup_tmp.log
  tail -n 15 /home/nn/rsync_logs/backup_tmp.log | tee -a /home/nn/rsync_logs/backup_page.log
  echo "--------------------------------------------"
  echo "--[ Backup /nnvault/Media/Music/. /music ]--"
  echo "--------------------------------------------"
  sh -c 'echo "--------------------------------------------" >> /home/nn/rsync_logs/backup_page.log'
  sh -c 'echo "--[ Backup /nnvault/Media/Music/. /music ]--" >> /home/nn/rsync_logs/backup_page.log'
  sh -c 'echo "--------------------------------------------" >> /home/nn/rsync_logs/backup_page.log'
  rsync -avh --progress --delete --stats --ignore-existing --ignore-errors -s -e "ssh" --rsync-path="rsync" /nnvault/Media/Music/. /music/ --log-file=/home/nn/rsync_logs/backup_tmp.log
  tail -n 15 /home/nn/rsync_logs/backup_tmp.log | tee -a /home/nn/rsync_logs/backup_page.log
  #Copy backup_page with date stamp for archive on server
  cp /home/nn/rsync_logs/backup_page.log /home/nn/rsync_logs/backup_"$(date +%Y-%m-%d_%H%M%S)".log
  #Copy backup_page to NNBackup logging folder
  cp /home/nn/rsync_logs/backup_page.log /nnvault/Files/NNServer/NNBackup/Logs/backup_"$(date +%Y-%m-%d_%H%M%S)".log
  fi
else
  echo "Error : NNVault Not Mounted"
fi
#delete temp files
sudo rm /home/nn/rsync_logs/backup_tmp.log
sudo rm /home/nn/rsync_logs/backup_page.log
#shutsdown the server
/sbin/shutdown -h now
